import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { DemovieError, execCapture, findProjectRoot, loadProject, toPosix, writeFileAtomic } from "@demovie/core";
import type { CommandContext } from "../context.ts";
import { ask } from "../lib/prompts.ts";
import type { CommandResult } from "../output.ts";

/** The composite action lives in the demovie repo; release.yml moves the `v0` tag to every 0.x release (SPEC §15.2). */
export const ACTION_REF = "enszrlu/demovie/packages/action@v0";

/** Agent CLI versions this release of demovie was tested with (DECISIONS); `ci init` pins the installed one if any. */
export const TESTED_AGENT_VERSIONS = { claude: "2.1.247", codex: "0.156.1" } as const;

/** The installed agent CLI's version (x.y.z from `--version`), else the tested one. */
async function agentVersion(agent: "claude" | "codex"): Promise<string> {
  const r = await execCapture(agent, ["--version"]).catch(() => null);
  return r?.code === 0
    ? (r.stdout.match(/\d+\.\d+\.\d+/)?.[0] ?? TESTED_AGENT_VERSIONS[agent])
    : TESTED_AGENT_VERSIONS[agent];
}

export function workflowYaml(o: { workingDirectory: string; agent: "claude" | "codex"; agentVersion: string }): string {
  const key = o.agent === "codex" ? "OPENAI_API_KEY" : "ANTHROPIC_API_KEY";
  return `# Generated by \`npx demovie ci init\`: a changelog clip for every release, made by your agent from real captures.
# Secrets: ${key} (an API key, not a subscription), DEMOVIE_USER and DEMOVIE_PASSWORD (the demo login).
name: demovie

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      since:
        description: "Git ref to summarize changes from (default: the previous tag)"
        required: false
  # Vercel preview deployments: uncomment to make a clip for each successful preview. This runs the commit that was
  # deployed, with the secrets below: only enable it when every preview comes from a branch you trust (no forks).
  # deployment_status:

permissions:
  contents: write # attach the videos to the release
  pull-requests: write # comment on pull requests

concurrency:
  group: demovie-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  video:
    if: github.event_name != 'deployment_status' || github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # tags and history for \`demovie changes\`
          persist-credentials: false # the agent never sees a git token; the action passes one only to its report step
      - uses: ${ACTION_REF}
        with:
          agent: ${o.agent}
          agent-version: "${o.agentVersion}" # pinned: bump it deliberately
          type: changelog
          since: \${{ inputs.since }}
          app-url: \${{ github.event.deployment_status.environment_url }}
          working-directory: ${o.workingDirectory}
        env:
          ${key}: \${{ secrets.${key} }}
          DEMOVIE_USER: \${{ secrets.DEMOVIE_USER }}
          DEMOVIE_PASSWORD: \${{ secrets.DEMOVIE_PASSWORD }}
          # VERCEL_AUTOMATION_BYPASS_SECRET: \${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          # ELEVENLABS_API_KEY: \${{ secrets.ELEVENLABS_API_KEY }}
`;
}

/** `demovie ci init [--provider github]` (SPEC §15.2): write `.github/workflows/demovie.yml` after confirmation. */
export async function run(ctx: CommandContext, options: { provider?: string }): Promise<CommandResult> {
  if (options.provider && options.provider !== "github")
    throw new DemovieError("E_USAGE", `CI provider "${options.provider}" is not supported`, "use --provider github");
  const root = findProjectRoot(ctx.cwd) ?? ctx.cwd;
  const agents = findProjectRoot(ctx.cwd) ? (await loadProject(ctx.cwd)).config.agents : [];
  const agent = agents.includes("claude") || !agents.includes("codex") ? "claude" : "codex";
  const top = await execCapture("git", ["rev-parse", "--show-toplevel"], { cwd: root });
  const repoRoot = top.code === 0 ? top.stdout.trim() : root;
  const workingDirectory = toPosix(path.relative(repoRoot, root)) || ".";
  const file = path.join(repoRoot, ".github", "workflows", "demovie.yml");
  const content = workflowYaml({ workingDirectory, agent, agentVersion: await agentVersion(agent) });
  const rel = path.relative(ctx.cwd, file);
  const exists = existsSync(file);
  const unchanged = exists && readFileSync(file, "utf8") === content;
  if (!unchanged) {
    if (!ctx.yes) {
      if (!ctx.interactive)
        throw new DemovieError(
          "E_USAGE",
          `writing ${rel} needs confirmation`,
          "re-run with --yes to write the workflow",
        );
      if (!(await ask.confirm(`${exists ? "Overwrite" : "Write"} ${rel}?`, !exists)))
        throw new DemovieError(
          "E_USAGE",
          "cancelled: the workflow was not written",
          "re-run and confirm, or pass --yes",
        );
    }
    await writeFileAtomic(file, content);
  }
  const secret = agent === "codex" ? "OPENAI_API_KEY" : "ANTHROPIC_API_KEY";
  return {
    data: {
      file: rel,
      written: !unchanged,
      workingDirectory,
      agent,
      action: ACTION_REF,
      secrets: [secret, "DEMOVIE_USER", "DEMOVIE_PASSWORD"],
    },
    human: [
      unchanged ? `${rel} is up to date` : `wrote ${rel}`,
      `Add repository secrets: ${secret} (an API key), DEMOVIE_USER and DEMOVIE_PASSWORD.`,
      "Then publish a release, or run the workflow from the Actions tab.",
    ],
  };
}
