import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { DemovieError, execCapture, findProjectRoot, loadProject, toPosix, writeFileAtomic } from "@demovie/core";
import type { CommandContext } from "../context.ts";
import { ask } from "../lib/prompts.ts";
import type { CommandResult } from "../output.ts";

/** Until the repo is published the action is referenced with an `<owner>` placeholder (SPEC §15.2). */
export const ACTION_REF = "<owner>/demovie/packages/action@v0";

export function workflowYaml(o: { workingDirectory: string; agent: "claude" | "codex" }): string {
  const key = o.agent === "codex" ? "OPENAI_API_KEY" : "ANTHROPIC_API_KEY";
  return `# Generated by \`npx demovie ci init\`: a changelog clip for every release, made by your agent from real captures.
# Secrets: ${key} (an API key, not a subscription), DEMOVIE_USER and DEMOVIE_PASSWORD (the demo login).
name: demovie

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      since:
        description: "Git ref to summarize changes from (default: the previous tag)"
        required: false
  # Vercel preview deployments: uncomment to make a clip for each successful preview.
  # deployment_status:

permissions:
  contents: write # attach the videos to the release
  pull-requests: write # comment on pull requests

concurrency:
  group: demovie-\${{ github.ref }}
  cancel-in-progress: true

jobs:
  video:
    if: github.event_name != 'deployment_status' || github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # tags and history for \`demovie changes\`
      - uses: ${ACTION_REF}
        with:
          agent: ${o.agent}
          type: changelog
          since: \${{ inputs.since }}
          app-url: \${{ github.event.deployment_status.environment_url }}
          working-directory: ${o.workingDirectory}
        env:
          ${key}: \${{ secrets.${key} }}
          DEMOVIE_USER: \${{ secrets.DEMOVIE_USER }}
          DEMOVIE_PASSWORD: \${{ secrets.DEMOVIE_PASSWORD }}
          # VERCEL_AUTOMATION_BYPASS_SECRET: \${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}
          # ELEVENLABS_API_KEY: \${{ secrets.ELEVENLABS_API_KEY }}
`;
}

/** `demovie ci init [--provider github]` (SPEC §15.2): write `.github/workflows/demovie.yml` after confirmation. */
export async function run(ctx: CommandContext, options: { provider?: string }): Promise<CommandResult> {
  if (options.provider && options.provider !== "github")
    throw new DemovieError("E_USAGE", `CI provider "${options.provider}" is not supported`, "use --provider github");
  const root = findProjectRoot(ctx.cwd) ?? ctx.cwd;
  const agents = findProjectRoot(ctx.cwd) ? (await loadProject(ctx.cwd)).config.agents : [];
  const agent = agents.includes("claude") || !agents.includes("codex") ? "claude" : "codex";
  const top = await execCapture("git", ["rev-parse", "--show-toplevel"], { cwd: root });
  const repoRoot = top.code === 0 ? top.stdout.trim() : root;
  const workingDirectory = toPosix(path.relative(repoRoot, root)) || ".";
  const file = path.join(repoRoot, ".github", "workflows", "demovie.yml");
  const content = workflowYaml({ workingDirectory, agent });
  const rel = path.relative(ctx.cwd, file);
  const exists = existsSync(file);
  const unchanged = exists && readFileSync(file, "utf8") === content;
  if (!unchanged) {
    if (!ctx.yes) {
      if (!ctx.interactive)
        throw new DemovieError(
          "E_USAGE",
          `writing ${rel} needs confirmation`,
          "re-run with --yes to write the workflow",
        );
      if (!(await ask.confirm(`${exists ? "Overwrite" : "Write"} ${rel}?`, !exists)))
        throw new DemovieError(
          "E_USAGE",
          "cancelled: the workflow was not written",
          "re-run and confirm, or pass --yes",
        );
    }
    await writeFileAtomic(file, content);
  }
  const secret = agent === "codex" ? "OPENAI_API_KEY" : "ANTHROPIC_API_KEY";
  return {
    data: {
      file: rel,
      written: !unchanged,
      workingDirectory,
      agent,
      action: ACTION_REF,
      secrets: [secret, "DEMOVIE_USER", "DEMOVIE_PASSWORD"],
    },
    human: [
      unchanged ? `${rel} is up to date` : `wrote ${rel}`,
      `Add repository secrets: ${secret} (an API key), DEMOVIE_USER and DEMOVIE_PASSWORD.`,
      `Replace <owner> in "${ACTION_REF}" once the demovie action is published, then publish a release or run the workflow.`,
    ],
  };
}
