/**
 * Build the Agent Skill and its distributions (SPEC §14.1–14.2):
 *  - generates references/runtime-api.md (from the runtime's exports) and references/qa-rules.md (from the QA rules);
 *  - stamps SKILL.md `metadata.version` with the CLI version;
 *  - copies the skill to plugins/demovie/skills/demovie and writes the plugin manifest, .mcp.json and the
 *    marketplace (.claude-plugin/marketplace.json).
 * Files are only rewritten when their content changes. Runs as the @demovie/skill package build.
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { RULES } from "../packages/qa/src/rules.ts";
import { repoRoot } from "./lib/repo.ts";
import { renderRuntimeApi } from "./lib/runtime-api.ts";

const version = (
  JSON.parse(readFileSync(path.join(repoRoot, "packages/cli/package.json"), "utf8")) as { version: string }
).version;
const skillDir = path.join(repoRoot, "packages/skill/demovie");
const pluginDir = path.join(repoRoot, "plugins/demovie");
const changed: string[] = [];

function write(file: string, content: string): void {
  if (existsSync(file) && readFileSync(file, "utf8") === content) return;
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, content);
  changed.push(path.relative(repoRoot, file));
}

/** JSON the way Biome formats it: objects expanded, arrays of primitives inline when they fit in 120 columns. */
export function formatJson(value: unknown, indent = 0, prefix = 0): string {
  const pad = "  ".repeat(indent);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const inline = `[${value.map((v) => JSON.stringify(v)).join(", ")}]`;
    if (value.every((v) => v === null || typeof v !== "object") && prefix + inline.length + 1 <= 120) return inline;
    return `[\n${value.map((v) => `${pad}  ${formatJson(v, indent + 1, pad.length + 2)}`).join(",\n")}\n${pad}]`;
  }
  if (value && typeof value === "object") {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined);
    if (entries.length === 0) return "{}";
    return `{\n${entries
      .map(([k, v]) => {
        const head = `${pad}  ${JSON.stringify(k)}: `;
        return `${head}${formatJson(v, indent + 1, head.length)}`;
      })
      .join(",\n")}\n${pad}}`;
  }
  return JSON.stringify(value);
}

const writeJson = (file: string, value: unknown) => write(file, `${formatJson(value)}\n`);

export function renderQaRules(): string {
  const cell = (s: string) => s.replace(/\|/g, "\\|");
  return [
    "<!-- Generated by scripts/build-skill.ts from packages/qa/src/rules.ts. Do not edit; run `pnpm skill:build`. -->",
    "# QA rules",
    "",
    "`npx demovie qa <slug> --format all` runs every rule on frames sampled at 10 fps and writes `qa.json`. Errors block",
    "the final render; warnings are reported (`--strict` turns them into errors). Only the user may waive a rule",
    "(`video.json` `qa.ignore`). Each failure in `qa.json` has occurrences (time, box, detail) and the fix below.",
    "",
    "| ID | Severity | Rule | Measurement |",
    "|---|---|---|---|",
    ...RULES.map((r) => `| ${r.id} | ${r.severity} | ${cell(r.title)} | ${cell(r.measurement)} |`),
    "",
    "## Fixes",
    "",
    ...RULES.map((r) => `- **${r.id} ${r.title}** — ${r.fix}`),
    "",
  ].join("\n");
}

// 1. generated references
write(path.join(skillDir, "references/runtime-api.md"), renderRuntimeApi());
write(path.join(skillDir, "references/qa-rules.md"), renderQaRules());

// 2. version stamp
const skillFile = path.join(skillDir, "SKILL.md");
const skill = readFileSync(skillFile, "utf8");
const stamped = skill.replace(/(\nmetadata:\n {2}version: )"[^"]*"/, `$1"${version}"`);
if (!/\nmetadata:\n {2}version: "/.test(skill)) throw new Error("SKILL.md frontmatter needs metadata.version");
write(skillFile, stamped);

// 3. Claude Code plugin + marketplace
const description =
  "Make accurate, on-brand motion-graphics videos of your real web app: real captures, a motion runtime, QA and rendering, driven by your coding agent.";
const pluginSkill = path.join(pluginDir, "skills/demovie");
const before = existsSync(pluginSkill) ? JSON.stringify(snapshot(pluginSkill)) : "";
rmSync(pluginSkill, { recursive: true, force: true });
cpSync(skillDir, pluginSkill, { recursive: true });
if (JSON.stringify(snapshot(pluginSkill)) !== before) changed.push(path.relative(repoRoot, pluginSkill));
writeJson(path.join(pluginDir, ".claude-plugin/plugin.json"), {
  name: "demovie",
  version,
  description,
  author: { name: "demovie contributors" },
  license: "MIT",
  keywords: ["video", "motion-graphics", "product-video", "launch-video", "changelog", "agent-skills", "mcp"],
});
writeJson(path.join(pluginDir, ".mcp.json"), {
  mcpServers: { demovie: { command: "npx", args: ["-y", "demovie", "mcp"] } },
});
writeJson(path.join(repoRoot, ".claude-plugin/marketplace.json"), {
  name: "demovie",
  owner: { name: "demovie contributors" },
  metadata: {
    description: "The demovie plugin for Claude Code: the Agent Skill plus the demovie MCP server.",
    version,
  },
  plugins: [{ name: "demovie", source: "./plugins/demovie", description, version, license: "MIT" }],
});

function snapshot(dir: string): Record<string, string> {
  const out: Record<string, string> = {};
  const walk = (d: string) => {
    for (const entry of readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) walk(full);
      else out[path.relative(dir, full)] = readFileSync(full, "utf8");
    }
  };
  walk(dir);
  return out;
}

process.stdout.write(
  `skill ${version}: ${changed.length ? `updated ${changed.join(", ")}` : "up to date"} · plugin + marketplace ok\n`,
);
