/**
 * License policy (SPEC §5.4):
 *  1. Nothing in the whole workspace tree (prod + dev) may be GPL, AGPL or LGPL, and no Remotion package may appear.
 *  2. Every production dependency of a published package (`demovie`, `@demovie/runtime`) must use an allowed license.
 *  3. Every audio file in the repo must be generated by demovie (listed in a provenance file).
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { listRepoFiles, repoRoot } from "./lib/repo.ts";

interface PnpmLicenseEntry {
  name: string;
  versions: string[];
  license: string;
  paths: string[];
}

const ALLOWED = new Set([
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "0BSD",
  "MPL-2.0",
  "CC0-1.0",
  "OFL-1.1",
  "SIL OPEN FONT LICENSE",
]);

/** Packages whose license string isn't SPDX but is explicitly accepted by the spec. */
const EXCEPTIONS: Record<string, string> = {
  gsap: "GSAP standard 'no charge' license; SPEC §5.2 chooses GSAP explicitly (free for commercial use, plugins included).",
};

const FORBIDDEN = /\b(A|L)?GPL\b|GNU (Affero |Lesser )?General Public/i;

function licenses(args: string[]): Record<string, PnpmLicenseEntry[]> {
  const out = execFileSync("pnpm", ["licenses", "list", "--json", ...args], {
    cwd: repoRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
    maxBuffer: 64 * 1024 * 1024,
  });
  // pnpm prints a plain sentence (not JSON) when a package has no dependencies.
  return out.trim().startsWith("{") ? (JSON.parse(out) as Record<string, PnpmLicenseEntry[]>) : {};
}

/** An SPDX expression is allowed when every AND-term (or at least one OR-alternative) is allowed. */
export function isAllowedLicense(expression: string): boolean {
  const expr = expression.replace(/[()]/g, "").trim();
  if (ALLOWED.has(expr)) return true;
  if (/\sOR\s/.test(expr)) return expr.split(/\s+OR\s+/).some((part) => isAllowedLicense(part));
  if (/\sAND\s/.test(expr)) return expr.split(/\s+AND\s+/).every((part) => isAllowedLicense(part));
  return false;
}

export function isForbiddenLicense(expression: string): boolean {
  const expr = expression.replace(/[()]/g, "").trim();
  if (/\sOR\s/.test(expr)) return expr.split(/\s+OR\s+/).every((part) => isForbiddenLicense(part));
  return FORBIDDEN.test(expr);
}

function main(): void {
  const problems: string[] = [];
  let checked = 0;

  // 1. Whole workspace: no GPL family, no Remotion.
  const all = licenses(["-r"]);
  for (const [license, entries] of Object.entries(all)) {
    for (const entry of entries) {
      checked++;
      if (entry.name === "remotion" || entry.name.startsWith("@remotion/")) {
        problems.push(`${entry.name}: Remotion packages are forbidden (SPEC §1.3)`);
      }
      if (isForbiddenLicense(license))
        problems.push(`${entry.name}@${entry.versions.join(",")}: forbidden license ${license}`);
    }
  }

  // 2. Production trees of the published packages: allow-list only.
  const published = ["demovie", "@demovie/runtime"];
  const prodNames = new Set<string>();
  for (const pkg of published) {
    const prod = licenses(["--prod", "--filter", pkg]);
    for (const [license, entries] of Object.entries(prod)) {
      for (const entry of entries) {
        prodNames.add(entry.name);
        if (EXCEPTIONS[entry.name]) continue;
        if (!isAllowedLicense(license)) {
          problems.push(
            `${entry.name}@${entry.versions.join(",")} (dependency of ${pkg}): license "${license}" is not allowed`,
          );
        }
      }
    }
  }

  // 3. Audio assets must come from demovie generators.
  // The bad-audio QA fixture deliberately ships locally generated test tones (ffmpeg lavfi sine) without provenance,
  // so that QA rule DM-A04 has something to catch. Nothing else is exempt.
  const EXEMPT = /^examples\/compositions\/bad-audio\/audio\//;
  const audioFiles = listRepoFiles().filter((f) => /\.(wav|mp3|aac|m4a|ogg|flac|opus)$/i.test(f) && !EXEMPT.test(f));
  for (const file of audioFiles) {
    const provenance = path.join(repoRoot, path.dirname(file), "provenance.json");
    const listed =
      existsSync(provenance) &&
      (JSON.parse(readFileSync(provenance, "utf8")) as { files?: { file: string }[] }).files?.some(
        (entry) => entry.file === path.basename(file),
      );
    if (!listed) problems.push(`${file}: audio file without a provenance.json entry (SPEC §5.4, §13.4)`);
  }

  if (problems.length > 0) {
    process.stderr.write(`License check failed:\n${problems.map((p) => `  - ${p}`).join("\n")}\n`);
    process.exit(1);
  }
  process.stdout.write(
    `License check OK: ${checked} packages scanned, ${prodNames.size} production dependencies of ${published.join(", ")} allowed, ${audioFiles.length} audio files with provenance.\n`,
  );
}

if (import.meta.url === `file://${process.argv[1]}`) main();
